"""Incident Renderer.

Auto-generates structured postmortem markdown documents from Incident objects.
Output is sanitised (no credentials or raw hostnames) and suitable for
committing to a public or internal repo.

Usage:
    from incident_render import render_postmortem, render_summary_report
    md = render_postmortem(incident)
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from incident_manager import Incident, IncidentStatus


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_POSTMORTEM = """\
# Postmortem: {title}

| Field | Value |
|---|---|
| **Incident ID** | `{id}` |
| **Severity** | {severity} |
| **Service** | `{service}` |
| **SLO** | `{slo_id}` |
| **Status** | {status} |
| **Opened** | {opened_at} |
| **Resolved** | {resolved_at} |
| **Time to Resolution** | {ttr} |

---

## Summary

{description}

---

## Impact

| Metric | Value |
|---|---|
| Burn Rate at Detection | {burn_rate:.2f}x |
| Error Budget Remaining | {budget_remaining:.1%} |
| Escalated | {escalated} |

---

## Timeline

{timeline}

---

## Root Cause

{root_cause}

---

## Action Items

{action_items}

---

## Contributing Factors

{contributing_factors}

---

*Generated by SRE Reliability Pipeline · {generated_at}*
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_postmortem(incident: Incident) -> str:
    """Render a full postmortem markdown document for a single incident."""
    return _POSTMORTEM.format(
        title=incident.title,
        id=incident.id,
        severity=incident.severity.value,
        service=incident.service,
        slo_id=incident.slo_id,
        status=incident.status.value,
        opened_at=_fmt_ts(incident.opened_at),
        resolved_at=_fmt_ts(incident.resolved_at) if incident.resolved_at else "_Not yet resolved_",
        ttr=_fmt_ttr(incident.ttr_minutes),
        description=incident.description or "_No description provided._",
        burn_rate=incident.burn_rate,
        budget_remaining=incident.budget_remaining,
        escalated="Yes" if incident.escalated else "No",
        timeline=_render_timeline(incident),
        root_cause=incident.root_cause or "_Root cause under investigation._",
        action_items=_render_action_items(incident.action_items),
        contributing_factors=_render_contributing_factors(incident),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
    )


def render_summary_report(incidents: List[Incident]) -> str:
    """Render a summary table for multiple incidents."""
    resolved = [i for i in incidents if i.ttr_minutes is not None]
    avg_ttr = (
        sum(i.ttr_minutes for i in resolved) / len(resolved)  # type: ignore[misc]
        if resolved else 0.0
    )

    lines = [
        "# SRE Incident Summary Report",
        "",
        f"**Total Incidents:** {len(incidents)}  ",
        f"**Resolved:** {len(resolved)}  ",
        f"**Average TTR:** {_fmt_ttr(avg_ttr)}  ",
        "",
        "---",
        "",
        "## Incidents",
        "",
        "| ID | Severity | Service | Status | TTR |",
        "|---|---|---|---|---|",
    ]

    for inc in sorted(incidents, key=lambda i: i.opened_at, reverse=True):
        lines.append(
            f"| `{inc.id}` | {inc.severity.value} | "
            f"`{inc.service}` | {inc.status.value} | {_fmt_ttr(inc.ttr_minutes)} |"
        )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _fmt_ts(ts: Optional[str]) -> str:
    if not ts:
        return "—"
    try:
        dt = datetime.fromisoformat(ts)
        return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except ValueError:
        return ts


def _fmt_ttr(minutes: Optional[float]) -> str:
    if minutes is None:
        return "N/A (unresolved)"
    if minutes < 60:
        return f"{minutes:.0f} min"
    return f"{minutes / 60:.1f} h ({minutes:.0f} min)"


def _render_timeline(incident: Incident) -> str:
    if not incident.timeline:
        return "_No timeline events recorded._"
    lines = []
    for evt in incident.timeline:
        ts = _fmt_ts(evt.timestamp)
        lines.append(
            f"- **{ts}** — `{evt.event_type}`: {evt.description} "
            f"*(actor: {evt.actor})*"
        )
    return "\n".join(lines)


def _render_action_items(items: List[str]) -> str:
    if not items:
        return "_No action items recorded._"
    return "\n".join(f"- [ ] {item}" for item in items)


def _render_contributing_factors(incident: Incident) -> str:
    factors: List[str] = []
    if incident.burn_rate >= 14.4:
        factors.append(
            f"Critical burn rate ({incident.burn_rate:.1f}x) — rapid budget depletion"
        )
    elif incident.burn_rate >= 6.0:
        factors.append(
            f"Elevated burn rate ({incident.burn_rate:.1f}x) — accelerated consumption"
        )
    if incident.budget_remaining < 0.05:
        factors.append(
            f"Error budget critically low ({incident.budget_remaining:.1%} remaining)"
        )
    if incident.escalated:
        factors.append(
            "Incident required escalation due to resolution time exceeding SLA threshold"
        )
    if not factors:
        factors.append("No additional contributing factors identified.")
    return "\n".join(f"- {f}" for f in factors)
